### PR TITLE
Reverting publish to v2

### PR DESCRIPTION
**Pull request by yogeshbdeshpande**

### CODE REVIEW

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by henkbirkholz** [comment]
Why are you messing with the i-d-template? https://github.com/ietf-wg-scitt/draft-ietf-scitt-software-use-cases/commit/a533b509d694af81942bd44aade2f5bbfb929b2e does not build anymore.

**Comment by yogeshbdeshpande** [comment]
@henkbirkholz It is not building since long time, I tried many fixes, yet no success. Please check the commit history for failure!

**Comment by yogeshbdeshpande** [comment]
> @henkbirkholz It is not building since long time, I tried many fixes, yet no success. Please check the commit history for failure!

Also it builds on my fork, without any issues!

**Pull request merged**
